# Basic Statistical Testing

In [1]:
import pandas as pd
import numpy as np
import scipy as stats

In [2]:
df = pd.read_csv('datasets/grades.csv')
df.head()

,student_id,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
0,B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,2015-11-02 06:55:34.282000000,83.030552,2015-11-09 02:22:58.938000000,67.164441,2015-11-12 08:58:33.998000000,53.011553,2015-11-16 01:21:24.663000000,47.710398,2015-11-20 13:24:59.692000000,38.168318,2015-11-22 18:31:15.934000000
1,98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000
2,D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000
3,FFDF2B2C-F514-EF7F-6538-A6A53518E9DC,86.030665,2016-04-30 06:50:39.801000000,68.824532,2016-04-30 17:20:38.727000000,61.942079,2016-05-12 07:47:16.326000000,49.553663,2016-05-07 16:09:20.485000000,49.553663,2016-05-24 12:51:18.016000000,44.598297,2016-05-26 08:09:12.058000000
4,5ECBEEB6-F1CE-80AE-3164-E45E99473FB4,64.813800,2015-12-13 17:06:10.750000000,51.491040,2015-12-14 12:25:12.056000000,41.932832,2015-12-29 14:25:22.594000000,36.929549,2015-12-28 01:29:55.901000000,33.236594,2015-12-29 14:46:06.628000000,33.236594,2016-01-05 01:06:59.546000000

In [3]:
df.shape

(2315, 13)

In [4]:
print('There are {} rows and {} columns'.format(df.shape[0], df.shape[1]))

There are 2315 rows and 13 columns

In [5]:
early_finishers=df[pd.to_datetime(df['assignment1_submission']) < '2016']
early_finishers.head()

,student_id,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
0,B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,2015-11-02 06:55:34.282000000,83.030552,2015-11-09 02:22:58.938000000,67.164441,2015-11-12 08:58:33.998000000,53.011553,2015-11-16 01:21:24.663000000,47.710398,2015-11-20 13:24:59.692000000,38.168318,2015-11-22 18:31:15.934000000
1,98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000
4,5ECBEEB6-F1CE-80AE-3164-E45E99473FB4,64.813800,2015-12-13 17:06:10.750000000,51.491040,2015-12-14 12:25:12.056000000,41.932832,2015-12-29 14:25:22.594000000,36.929549,2015-12-28 01:29:55.901000000,33.236594,2015-12-29 14:46:06.628000000,33.236594,2016-01-05 01:06:59.546000000
5,D09000A0-827B-C0FF-3433-BF8FF286E15B,71.647278,2015-12-28 04:35:32.836000000,64.052550,2016-01-03 21:05:38.392000000,64.752550,2016-01-07 08:55:43.692000000,57.467295,2016-01-11 00:45:28.706000000,57.467295,2016-01-11 00:54:13.579000000,57.467295,2016-01-20 19:54:46.166000000
8,C9D51293-BD58-F113-4167-A7C0BAFCB6E5,66.595568,2015-12-25 02:29:28.415000000,52.916454,2015-12-31 01:42:30.046000000,48.344809,2016-01-05 23:34:02.180000000,47.444809,2016-01-02 07:48:42.517000000,37.955847,2016-01-03 21:27:04.266000000,37.955847,2016-01-19 15:24:31.060000000

In [6]:
late_finishers = df[pd.to_datetime(df['assignment1_submission']) >= '2016']
late_finishers

,student_id,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
2,D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000
3,FFDF2B2C-F514-EF7F-6538-A6A53518E9DC,86.030665,2016-04-30 06:50:39.801000000,68.824532,2016-04-30 17:20:38.727000000,61.942079,2016-05-12 07:47:16.326000000,49.553663,2016-05-07 16:09:20.485000000,49.553663,2016-05-24 12:51:18.016000000,44.598297,2016-05-26 08:09:12.058000000
6,3217BE3F-E4B0-C3B6-9F64-462456819CE4,87.498744,2016-03-05 11:05:25.408000000,69.998995,2016-03-09 07:29:52.405000000,55.999196,2016-03-16 22:31:24.316000000,50.399276,2016-03-18 07:19:26.032000000,45.359349,2016-03-19 10:35:41.869000000,45.359349,2016-03-23 14:02:00.987000000
7,F1CB5AA1-B3DE-5460-FAFF-BE951FD38B5F,80.576090,2016-01-24 18:24:25.619000000,72.518481,2016-01-27 13:37:12.943000000,65.266633,2016-01-30 14:34:36.581000000,65.266633,2016-02-03 22:08:49.002000000,65.266633,2016-02-16 14:22:23.664000000,65.266633,2016-02-18 08:35:04.796000000
9,E2C617C2-4654-622C-AB50-1550C4BE42A0,59.270882,2016-03-06 12:06:26.185000000,59.270882,2016-03-13 02:07:25.289000000,53.343794,2016-03-17 07:30:09.241000000,53.343794,2016-03-20 21:45:56.229000000,42.675035,2016-03-27 15:55:04.414000000,38.407532,2016-03-30 20:33:13.554000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.215052,2016-01-23 09:19:40.494000000,77.772041,2016-01-26 08:38:13.085000000,69.994837,2016-01-29 15:04:34.705000000,62.995353,2016-02-06 12:51:00.647000000,50.396283,2016-02-11 15:44:08.113000000,50.396283,2016-02-14 09:03:33.466000000
2306,DDE0526B-7DA4-80E8-C2A6-D097F3826029,47.696703,2016-06-22 20:21:58.182000000,38.157363,2016-06-23 18:22:45.622000000,38.157363,2016-07-02 22:18:59.529000000,30.525890,2016-06-28 22:05:38.100000000,30.525890,2016-07-09 20:08:14.734000000,30.525890,2016-07-17 15:17:58.502000000
2307,1F51E050-78F7-F270-1B90-ED1BC0376763,94.595758,2016-01-20 23:22:16.592000000,85.136182,2016-01-27 22:30:29.914000000,76.622564,2016-01-31 15:39:45.088000000,68.960307,2016-02-06 21:43:05.836000000,62.064277,2016-02-14 18:52:48.594000000,49.651421,2016-02-19 20:36:16.121000000
2310,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,77.684611,2016-03-07 02:52:24.378000000,69.916150,2016-03-11 22:02:39.161000000,69.916150,2016-03-17 07:30:09.261000000,69.916150,2016-03-18 18:01:24.525000000,55.932920,2016-03-20 06:38:12.120000000,50.339628,2016-03-25 11:00:06.923000000
2313,1F51E050-78F7-F270-1B90-ED1BC0376763,87.268366,2016-04-03 09:04:51.646000000,87.268366,2016-04-08 19:24:29.095000000,87.268366,2016-04-12 05:43:33.853000000,69.814693,2016-04-14 10:43:58.104000000,55.851754,2016-04-19 05:37:19.322000000,55.851754,2016-04-23 03:44:06.813000000

In [7]:
# inverse version 
late_finishers = df[~df.index.isin(early_finishers.index)]
late_finishers

,student_id,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
2,D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000
3,FFDF2B2C-F514-EF7F-6538-A6A53518E9DC,86.030665,2016-04-30 06:50:39.801000000,68.824532,2016-04-30 17:20:38.727000000,61.942079,2016-05-12 07:47:16.326000000,49.553663,2016-05-07 16:09:20.485000000,49.553663,2016-05-24 12:51:18.016000000,44.598297,2016-05-26 08:09:12.058000000
6,3217BE3F-E4B0-C3B6-9F64-462456819CE4,87.498744,2016-03-05 11:05:25.408000000,69.998995,2016-03-09 07:29:52.405000000,55.999196,2016-03-16 22:31:24.316000000,50.399276,2016-03-18 07:19:26.032000000,45.359349,2016-03-19 10:35:41.869000000,45.359349,2016-03-23 14:02:00.987000000
7,F1CB5AA1-B3DE-5460-FAFF-BE951FD38B5F,80.576090,2016-01-24 18:24:25.619000000,72.518481,2016-01-27 13:37:12.943000000,65.266633,2016-01-30 14:34:36.581000000,65.266633,2016-02-03 22:08:49.002000000,65.266633,2016-02-16 14:22:23.664000000,65.266633,2016-02-18 08:35:04.796000000
9,E2C617C2-4654-622C-AB50-1550C4BE42A0,59.270882,2016-03-06 12:06:26.185000000,59.270882,2016-03-13 02:07:25.289000000,53.343794,2016-03-17 07:30:09.241000000,53.343794,2016-03-20 21:45:56.229000000,42.675035,2016-03-27 15:55:04.414000000,38.407532,2016-03-30 20:33:13.554000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.215052,2016-01-23 09:19:40.494000000,77.772041,2016-01-26 08:38:13.085000000,69.994837,2016-01-29 15:04:34.705000000,62.995353,2016-02-06 12:51:00.647000000,50.396283,2016-02-11 15:44:08.113000000,50.396283,2016-02-14 09:03:33.466000000
2306,DDE0526B-7DA4-80E8-C2A6-D097F3826029,47.696703,2016-06-22 20:21:58.182000000,38.157363,2016-06-23 18:22:45.622000000,38.157363,2016-07-02 22:18:59.529000000,30.525890,2016-06-28 22:05:38.100000000,30.525890,2016-07-09 20:08:14.734000000,30.525890,2016-07-17 15:17:58.502000000
2307,1F51E050-78F7-F270-1B90-ED1BC0376763,94.595758,2016-01-20 23:22:16.592000000,85.136182,2016-01-27 22:30:29.914000000,76.622564,2016-01-31 15:39:45.088000000,68.960307,2016-02-06 21:43:05.836000000,62.064277,2016-02-14 18:52:48.594000000,49.651421,2016-02-19 20:36:16.121000000
2310,DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2,77.684611,2016-03-07 02:52:24.378000000,69.916150,2016-03-11 22:02:39.161000000,69.916150,2016-03-17 07:30:09.261000000,69.916150,2016-03-18 18:01:24.525000000,55.932920,2016-03-20 06:38:12.120000000,50.339628,2016-03-25 11:00:06.923000000
2313,1F51E050-78F7-F270-1B90-ED1BC0376763,87.268366,2016-04-03 09:04:51.646000000,87.268366,2016-04-08 19:24:29.095000000,87.268366,2016-04-12 05:43:33.853000000,69.814693,2016-04-14 10:43:58.104000000,55.851754,2016-04-19 05:37:19.322000000,55.851754,2016-04-23 03:44:06.813000000

In [8]:
print(early_finishers['assignment1_grade'].mean())
print(late_finishers['assignment1_grade'].mean())

74.94728457024304
74.0450648477065

In [9]:
from scipy.stats import ttest_ind

In [10]:
ttest_ind(early_finishers['assignment1_grade'], late_finishers['assignment1_grade'])

TtestResult(statistic=np.float64(1.3223540853721598), pvalue=np.float64(0.18618101101713855), df=np.float64(2313.0))

In [11]:
print(ttest_ind(early_finishers['assignment2_grade'], late_finishers['assignment2_grade']))
print(ttest_ind(early_finishers['assignment3_grade'], late_finishers['assignment3_grade']))
print(ttest_ind(early_finishers['assignment4_grade'], late_finishers['assignment4_grade']))
print(ttest_ind(early_finishers['assignment5_grade'], late_finishers['assignment5_grade']))
print(ttest_ind(early_finishers['assignment6_grade'], late_finishers['assignment6_grade']))

TtestResult(statistic=np.float64(1.2514717608216366), pvalue=np.float64(0.2108889627004424), df=np.float64(2313.0))
TtestResult(statistic=np.float64(1.6133726558705392), pvalue=np.float64(0.10679998102227865), df=np.float64(2313.0))
TtestResult(statistic=np.float64(0.049671157386456125), pvalue=np.float64(0.960388729789337), df=np.float64(2313.0))
TtestResult(statistic=np.float64(-0.05279315545404755), pvalue=np.float64(0.9579012739746492), df=np.float64(2313.0))
TtestResult(statistic=np.float64(-0.11609743352612056), pvalue=np.float64(0.9075854011989656), df=np.float64(2313.0))

In [14]:
df1 = pd.DataFrame([np.random.random(100) for x in range(100)])
df1

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.573151,0.869621,0.828127,0.237580,0.261069,0.065086,0.332067,0.817673,0.154183,0.934168,...,0.485884,0.963054,0.689966,0.146535,0.450149,0.154023,0.605879,0.037195,0.384361,0.161552
1,0.213188,0.399062,0.832956,0.890604,0.800999,0.466427,0.519374,0.849094,0.651705,0.430231,...,0.118854,0.306733,0.337094,0.187750,0.169963,0.783039,0.833649,0.524868,0.861586,0.571390
2,0.039908,0.446255,0.938823,0.214244,0.260966,0.643331,0.718417,0.583649,0.650225,0.012011,...,0.443617,0.407181,0.145695,0.044140,0.192590,0.584244,0.168983,0.128254,0.218420,0.329999
3,0.076785,0.389282,0.235948,0.304730,0.271849,0.393358,0.985910,0.016328,0.242092,0.577153,...,0.895567,0.086232,0.391562,0.644564,0.330566,0.747448,0.796551,0.740392,0.632806,0.040722
4,0.728748,0.704937,0.635145,0.272497,0.121286,0.445007,0.954355,0.932252,0.000883,0.342628,...,0.453758,0.834546,0.188803,0.611792,0.038144,0.708380,0.458729,0.343468,0.732674,0.679516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.193395,0.430484,0.825827,0.940856,0.918899,0.700518,0.461605,0.097139,0.992958,0.243941,...,0.654504,0.637602,0.648975,0.789551,0.310261,0.510650,0.110854,0.639744,0.689597,0.708709
96,0.756735,0.195267,0.616138,0.556127,0.009533,0.362595,0.256153,0.596607,0.340930,0.754652,...,0.930261,0.775620,0.479322,0.532660,0.423031,0.092415,0.128405,0.447493,0.231681,0.016763
97,0.056407,0.906089,0.985115,0.968395,0.386325,0.584933,0.902074,0.708597,0.771454,0.100746,...,0.633868,0.247834,0.878838,0.013396,0.868579,0.853816,0.971415,0.397294,0.342565,0.958651
98,0.496636,0.450429,0.360587,0.617482,0.296668,0.585422,0.165557,0.264011,0.088788,0.112008,...,0.058814,0.728805,0.301752,0.287574,0.496065,0.006129,0.872493,0.508408,0.300555,0.334487
99,0.730326,0.706794,0.379489,0.781007,0.649055,0.715162,0.853434,0.074542,0.431263,0.944583,...,0.529222,0.009215,0.849098,0.124983,0.678676,0.471078,0.603617,0.661908,0.505195,0.098267

In [15]:
df2 = pd.DataFrame([np.random.random(100) for i in range(100)])
df2

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.059883,0.977832,0.676524,0.264992,0.963606,0.498067,0.215787,0.964367,0.125347,0.173164,...,0.307533,0.771872,0.451703,0.257501,0.443904,0.378910,0.225450,0.812509,0.460584,0.873172
1,0.696139,0.980338,0.449771,0.084932,0.464171,0.303186,0.492621,0.560948,0.342311,0.729573,...,0.483861,0.754964,0.026321,0.375339,0.959094,0.684214,0.470924,0.966679,0.212810,0.153707
2,0.561815,0.798732,0.033096,0.756130,0.537747,0.883849,0.693802,0.057189,0.879326,0.023856,...,0.736654,0.496897,0.655736,0.334267,0.094300,0.580042,0.707360,0.492422,0.973506,0.925753
3,0.585140,0.675591,0.357112,0.158871,0.645750,0.814619,0.348878,0.426970,0.302427,0.365452,...,0.370273,0.657711,0.860044,0.184248,0.946048,0.568963,0.828664,0.431227,0.385160,0.669913
4,0.242055,0.469767,0.125872,0.658877,0.366936,0.114687,0.861783,0.826057,0.966774,0.317487,...,0.258494,0.762871,0.045941,0.574464,0.341046,0.440446,0.359003,0.585677,0.459096,0.473581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.608010,0.763260,0.267117,0.936393,0.297067,0.188736,0.089766,0.962301,0.189154,0.242236,...,0.981496,0.826729,0.972048,0.688672,0.536387,0.733417,0.668892,0.675205,0.693209,0.130254
96,0.956560,0.254999,0.515180,0.156381,0.376388,0.715363,0.445618,0.679982,0.646934,0.909867,...,0.251390,0.148053,0.664975,0.997330,0.145707,0.099262,0.749974,0.877262,0.120436,0.817974
97,0.369700,0.157585,0.452325,0.076378,0.820243,0.926174,0.563981,0.336274,0.572437,0.607275,...,0.076031,0.589683,0.730686,0.913371,0.911104,0.814343,0.497686,0.822177,0.497927,0.500296
98,0.102451,0.967798,0.340015,0.794088,0.602948,0.469201,0.719999,0.503241,0.149709,0.205404,...,0.533525,0.517885,0.353949,0.768496,0.651148,0.089541,0.611661,0.843064,0.565830,0.223010
99,0.424466,0.294869,0.041738,0.681039,0.824693,0.573684,0.715173,0.209171,0.392397,0.626906,...,0.531241,0.061111,0.862430,0.205979,0.815056,0.126613,0.026542,0.010260,0.492843,0.401976

In [16]:
def test_columns(alpha=0.1):
    num_diff=0
    for col in df1.columns:
        teststat,pval=ttest_ind(df1[col],df2[col])
        if pval<=alpha:
            print("Col {} is statistically significantly different at alpha={}, pval={}".format(col,
                                                                                                alpha,
                                                                                                pval))
            num_diff=num_diff+1
    print("Total number different was {}, which is {}%".format(num_diff,
                                                               float(num_diff)/len(df1.columns)*100))
test_columns()

Col 6 is statistically significantly different at alpha=0.1, pval=0.06337065219631063
Col 11 is statistically significantly different at alpha=0.1, pval=0.05907879939257744
Col 21 is statistically significantly different at alpha=0.1, pval=0.005486694462442383
Col 27 is statistically significantly different at alpha=0.1, pval=0.07761326019517172
Col 37 is statistically significantly different at alpha=0.1, pval=0.06382271458484633
Col 39 is statistically significantly different at alpha=0.1, pval=0.0031900557841899003
Col 79 is statistically significantly different at alpha=0.1, pval=0.01357288007308309
Col 82 is statistically significantly different at alpha=0.1, pval=0.08132075781712077
Col 83 is statistically significantly different at alpha=0.1, pval=0.08355667204630535
Col 94 is statistically significantly different at alpha=0.1, pval=0.06651165997839445
Col 95 is statistically significantly different at alpha=0.1, pval=0.04576529510209316
Total number different was 11, which is 11.0%

In [17]:
test_columns(0.05)

Col 21 is statistically significantly different at alpha=0.05, pval=0.005486694462442383
Col 39 is statistically significantly different at alpha=0.05, pval=0.0031900557841899003
Col 79 is statistically significantly different at alpha=0.05, pval=0.01357288007308309
Col 95 is statistically significantly different at alpha=0.05, pval=0.04576529510209316
Total number different was 4, which is 4.0%

In [18]:
df2=pd.DataFrame([np.random.chisquare(df=1,size=100) for x in range(100)])
test_columns()

Col 0 is statistically significantly different at alpha=0.1, pval=2.5494561369160612e-05
Col 1 is statistically significantly different at alpha=0.1, pval=0.0005625619725203298
Col 2 is statistically significantly different at alpha=0.1, pval=0.0014178842944523801
Col 3 is statistically significantly different at alpha=0.1, pval=6.864527122766278e-05
Col 4 is statistically significantly different at alpha=0.1, pval=0.00022985423407589336
Col 5 is statistically significantly different at alpha=0.1, pval=0.002671281781488459
Col 6 is statistically significantly different at alpha=0.1, pval=6.962490215002979e-05
Col 7 is statistically significantly different at alpha=0.1, pval=5.838191190019217e-05
Col 8 is statistically significantly different at alpha=0.1, pval=0.0010790058708880653
Col 9 is statistically significantly different at alpha=0.1, pval=0.026093781786386588
Col 10 is statistically significantly different at alpha=0.1, pval=0.0031875348283717316
Col 11 is statistically significantly different at alpha=0.1, pval=2.60532869909284e-06
Col 12 is statistically significantly different at alpha=0.1, pval=0.0014987953266729648
Col 13 is statistically significantly different at alpha=0.1, pval=0.011293103248194507
Col 14 is statistically significantly different at alpha=0.1, pval=0.001480521058685686
Col 15 is statistically significantly different at alpha=0.1, pval=0.00038246526368684186
Col 16 is statistically significantly different at alpha=0.1, pval=4.934517718089518e-05
Col 17 is statistically significantly different at alpha=0.1, pval=3.473587806953941e-05
Col 18 is statistically significantly different at alpha=0.1, pval=9.104108187110373e-05
Col 19 is statistically significantly different at alpha=0.1, pval=0.0015637973696382755
Col 20 is statistically significantly different at alpha=0.1, pval=0.0008078519125781196
Col 21 is statistically significantly different at alpha=0.1, pval=0.0009833725034829482
Col 22 is statistically significantly different at alpha=0.1, pval=1.1042724711838868e-05
Col 23 is statistically significantly different at alpha=0.1, pval=2.7815322298103355e-06
Col 24 is statistically significantly different at alpha=0.1, pval=0.0007284253613210714
Col 25 is statistically significantly different at alpha=0.1, pval=0.0010266748109266793
Col 26 is statistically significantly different at alpha=0.1, pval=0.00732083121742564
Col 27 is statistically significantly different at alpha=0.1, pval=0.010515144587395634
Col 28 is statistically significantly different at alpha=0.1, pval=0.0025442539561720072
Col 29 is statistically significantly different at alpha=0.1, pval=0.0032157795921432526
Col 30 is statistically significantly different at alpha=0.1, pval=0.0006480823858364664
Col 31 is statistically significantly different at alpha=0.1, pval=0.0024295968200682134
Col 32 is statistically significantly different at alpha=0.1, pval=0.002660652471373897
Col 33 is statistically significantly different at alpha=0.1, pval=1.897243726703688e-05
Col 34 is statistically significantly different at alpha=0.1, pval=0.001289694608506409
Col 35 is statistically significantly different at alpha=0.1, pval=0.00035993775761530914
Col 36 is statistically significantly different at alpha=0.1, pval=0.0009775558358870893
Col 37 is statistically significantly different at alpha=0.1, pval=0.0006089699712498757
Col 38 is statistically significantly different at alpha=0.1, pval=1.5661697073920528e-06
Col 39 is statistically significantly different at alpha=0.1, pval=6.68905914514566e-05
Col 40 is statistically significantly different at alpha=0.1, pval=0.02129627037301755
Col 41 is statistically significantly different at alpha=0.1, pval=0.0068959571020655065
Col 42 is statistically significantly different at alpha=0.1, pval=1.1679836230617593e-07
Col 43 is statistically significantly different at alpha=0.1, pval=1.4055373557089855e-05
Col 44 is statistically significantly different at alpha=0.1, pval=0.0015720307404793166
Col 45 is statistically significantly different at alpha=0.1, pval=0.01657030627833566
Col 46 is statistically significantly different at alpha=0.1, pval=0.001004166483620047
Col 47 is statistically significantly different at alpha=0.1, pval=0.00025167042114305924
Col 48 is statistically significantly different at alpha=0.1, pval=0.06182728448349616
Col 49 is statistically significantly different at alpha=0.1, pval=0.0224773219788611
Col 50 is statistically significantly different at alpha=0.1, pval=0.005681621552831883
Col 51 is statistically significantly different at alpha=0.1, pval=0.00018624042143333667
Col 52 is statistically significantly different at alpha=0.1, pval=0.00030089145005604394
Col 53 is statistically significantly different at alpha=0.1, pval=0.0023154616801761094
Col 54 is statistically significantly different at alpha=0.1, pval=0.00035307201334520136
Col 55 is statistically significantly different at alpha=0.1, pval=2.2508513599171478e-05
Col 56 is statistically significantly different at alpha=0.1, pval=0.004235948467341362
Col 57 is statistically significantly different at alpha=0.1, pval=1.8208380637932573e-05
Col 58 is statistically significantly different at alpha=0.1, pval=0.0014747008874822917
Col 59 is statistically significantly different at alpha=0.1, pval=0.014481290650735192
Col 60 is statistically significantly different at alpha=0.1, pval=0.0020107497131235694
Col 61 is statistically significantly different at alpha=0.1, pval=0.0017555671348462227
Col 62 is statistically significantly different at alpha=0.1, pval=0.005631276929360946
Col 63 is statistically significantly different at alpha=0.1, pval=5.33397810363491e-05
Col 64 is statistically significantly different at alpha=0.1, pval=0.0012543239117028735
Col 65 is statistically significantly different at alpha=0.1, pval=0.0005161432322124291
Col 66 is statistically significantly different at alpha=0.1, pval=0.0026080241294315232
Col 67 is statistically significantly different at alpha=0.1, pval=0.00023299604202877975
Col 68 is statistically significantly different at alpha=0.1, pval=0.0001509986180765494
Col 69 is statistically significantly different at alpha=0.1, pval=0.0004460524086381732
Col 70 is statistically significantly different at alpha=0.1, pval=0.0037247967280553346
Col 71 is statistically significantly different at alpha=0.1, pval=1.9278770268552488e-05
Col 72 is statistically significantly different at alpha=0.1, pval=7.31199507626812e-05
Col 73 is statistically significantly different at alpha=0.1, pval=0.001079583949814714
Col 74 is statistically significantly different at alpha=0.1, pval=0.0007622778259755664
Col 75 is statistically significantly different at alpha=0.1, pval=0.004589857181500093
Col 76 is statistically significantly different at alpha=0.1, pval=0.0022189990209241666
Col 77 is statistically significantly different at alpha=0.1, pval=0.0021173771702257347
Col 78 is statistically significantly different at alpha=0.1, pval=0.0007536753814929299
Col 79 is statistically significantly different at alpha=0.1, pval=6.6893512592248e-05
Col 80 is statistically significantly different at alpha=0.1, pval=0.0052085346994112216
Col 81 is statistically significantly different at alpha=0.1, pval=3.4209803016143324e-05
Col 82 is statistically significantly different at alpha=0.1, pval=0.0010554992368753122
Col 83 is statistically significantly different at alpha=0.1, pval=0.00022517762456652956
Col 84 is statistically significantly different at alpha=0.1, pval=0.027932412510308924
Col 85 is statistically significantly different at alpha=0.1, pval=0.000599142745386017
Col 86 is statistically significantly different at alpha=0.1, pval=0.005459728821229786
Col 87 is statistically significantly different at alpha=0.1, pval=0.0007495191658129027
Col 88 is statistically significantly different at alpha=0.1, pval=0.0013296481041258957
Col 89 is statistically significantly different at alpha=0.1, pval=0.0008932416121368603
Col 90 is statistically significantly different at alpha=0.1, pval=0.010649165013371726
Col 91 is statistically significantly different at alpha=0.1, pval=0.0002753690504540643
Col 92 is statistically significantly different at alpha=0.1, pval=0.0013299341797131713
Col 93 is statistically significantly different at alpha=0.1, pval=0.00030854103319410427
Col 94 is statistically significantly different at alpha=0.1, pval=0.00504363748139946
Col 95 is statistically significantly different at alpha=0.1, pval=0.00011200802549566347
Col 96 is statistically significantly different at alpha=0.1, pval=0.0006800393564864737
Col 97 is statistically significantly different at alpha=0.1, pval=7.344615680983015e-05
Col 98 is statistically significantly different at alpha=0.1, pval=0.0014091148328057395
Col 99 is statistically significantly different at alpha=0.1, pval=0.0043963922572718495
Total number different was 100, which is 100.0%

In [20]:
df2

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.661226,4.849516,0.042694,0.754831,3.550306,0.488328,1.004681,1.502210,2.057233,2.397043,...,0.207564,0.928544,1.715150,0.910601,1.027750,2.647596,0.082137,2.010151,1.230515,0.334879
1,0.011066,0.695954,0.292134,0.643110,0.921923,1.963768,0.097360,0.016244,0.219080,0.744876,...,0.178581,0.962644,0.357238,0.250180,1.082837,0.393079,1.803502,3.268493,1.640984,0.605938
2,0.588305,0.001610,0.250960,0.415122,0.058032,0.122881,3.441784,0.000871,0.508280,0.013143,...,0.603755,0.230095,1.790366,1.315058,1.898033,0.000076,0.002610,0.864857,0.248603,0.055437
3,0.275382,2.970499,0.599691,0.940638,0.306658,0.203809,0.153160,0.061673,0.431668,0.961237,...,0.831297,0.046506,0.234736,0.256009,0.518062,8.768219,0.238510,1.169276,0.087152,0.271246
4,0.048154,0.175825,0.001605,1.093542,0.077193,0.587103,1.826371,0.244040,0.941583,0.874403,...,2.481217,0.527775,0.798717,1.278281,0.293578,1.144158,0.349918,1.391525,0.994186,0.365236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4.235271,0.030439,0.008323,0.961902,0.039897,0.198456,0.405037,0.274661,0.028243,0.058244,...,0.310008,0.013950,0.484811,2.827933,2.242156,2.831840,0.521385,0.496736,1.951254,1.223129
96,5.888820,3.614982,0.152228,0.346547,2.231609,0.016377,5.178473,0.011665,0.194815,5.507559,...,0.017047,0.046842,0.150899,0.296438,0.080869,0.020051,0.358525,1.518756,2.455077,0.528251
97,0.175137,0.193492,0.060225,0.000090,1.928078,0.002942,3.274902,0.178786,0.087826,0.052351,...,0.835935,0.141265,0.410321,0.107107,0.999579,4.730285,0.540426,0.405161,3.562224,0.674332
98,0.004406,0.283475,0.669991,0.178090,0.123692,0.005235,1.346761,0.014612,1.153956,1.461745,...,0.371579,0.013219,0.099474,0.002664,0.006738,1.289005,0.439927,0.009092,0.224573,0.088481
99,0.004246,0.213986,0.059458,1.546801,5.273848,4.573840,0.190451,0.468457,0.712863,0.868813,...,0.603153,0.014496,0.054461,0.519614,0.010384,0.739277,0.018994,0.047131,0.505400,2.008195